---
title: "1-explore"
author: "bernard-liew"
date: "2021-02-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Load package

```{r}
# Helper
library (tidyverse)
library (skimr)
library (arsenal)
library (janitor)
library (rio)
library (lubridate)
```

# Import

```{r}
key <- import ("data/key.xlsx")

df <- import ("data/Data acl-rsi network analysis (relevant variables only) deidentified.xlsx",
              col_types = key$type,
              skip = 1)

names (df) <- key$new_header

df[, c(7)] <- ymd_hms(df[, c(7)])
df[, c(8)] <- ymd_hms(df[, c(8)])
```

# Explore

```{r}

# Check sex coding
unique (df$sex)
df <- df %>%
  mutate (sex = recode (sex,
                        Male = "m",
                        Female = "f"))

# Check presports level coding
unique (df$pre_sports_level)
df <- df %>%
  mutate (pre_sports_level = recode (pre_sports_level,
                        `High level competitive sports` = "competitive",
                        `Hihg level competitive sportd` = "competitive",
                        `Professional athlete` = "pro",
                        `Frequent sports` = "freq",
                        `Sports sometimes` = "some"))

# Check pre_sports_freq coding
unique (df$pre_sports_freq)
df <- df %>%
  mutate (pre_sports_freql = recode (pre_sports_freq,
                        `1-3 days per week` = "1-3days/wk",
                        `4-7 days per week` = "4-7days/wk",
                        `1-3 times per month` = "1-3days/mth"))

# Check rts_12 coding
unique(df$rts_12)
df <- df %>%
  mutate (rts_12 = recode (rts_12,
                        `Yes, at a lower level compared to before injury` = "yes_lower",
                        `Yes, at the same or higher level compared to before injury` = "yes_same_high",
                        `Yes, training only` = "yes_train",
                        `Training only` = "yes_train",
                        `No` = "no"))

# Check rts_6 coding
unique(df$rts_6)
df <- df %>%
  mutate (rts_6 = recode (rts_6,
                        `Yes, at a lower level compared to before injury` = "yes_lower",
                        `Yes, at the same or higher level compared to before injury` = "yes_same_high",
                        `Ypre` = "yes_same_high",
                        `Yes, training only` = "yes_train",
                        `Not applicable, I did not play sport before my knee injury` = "na_no_prior",
                        `No` = "no"))
skim (df)

# Check frequencies 
table (df$rts_6)
table (df$rts_12)
```

# Missing

```{r}
miss_df <- df %>%
  filter (!complete.cases(.))

```

# Export

```{r}
export (df,
        "output/dat_acl.RDS")
```

